### ISSUE TITLE
Question about the convergence order

### ISSUE THREAD

**Issue by cam1681** [XuezheMax/apollo#7]
It seems that the Quasi-Newton methods have second-order convergence. But in the loss figures you have shown in the README.md, it behaves like a first-order optimizer (It performs better than SGD, but shares similar learning curves). So, I am wondering why this happens, could you please explain for my confuse?

**Comment by XuezheMax** [comment]
Thanks for your question. Theoretically, Quasi-Newton methods have second-order convergence rate under non-stochastic convex setting. In deep learning, the objective function is stochastic and nonconvex, and there is no theoretical proof that Quasi-Newton methods hold the second-order convergence rate. Note that not only Quasi-Newton methods, but also Hessian-free methods, such as AdaHessian in Fig 1 do not have second-order convergence rate. But we can still see that the convergence rates of AdaHessian and Apollo are better than SGD and Adam in Fig 1. Moreover, in image classification with ResNet, there are some other factors which impact convergence rate, such as weight decay. Please see the effects of weight decay on convergence rate and generalization performance in Appendix E.2. Please let me know if you have other questions.
