### ISSUE TITLE
Using Approximate Hessian to steer training towards wide flat minima

### ISSUE THREAD

**Issue by evanatyourservice** [XuezheMax/apollo#9]
Hello! Since Apollo calculates an approximate hessian and this essentially describes the local loss landscape, I'm wondering if it can be used to steer training toward wide, flat minima vs. only minima, perhaps by adding a term using the hessian's max eigenvalues or something similar. This might need to be a term added to the loss, though, since the eigenvalues would want to be minimized, but I wonder if training could be steered toward lower hessian eigenvalues within the optimizer.

Just wondering if you guys ever looked into this or have any insights?

**Comment by XuezheMax** [comment]
Hi,

Thanks so much for this interesting idea. To be honest, we have not looked into this. I think if we want to minimize the eigenvalues via Apollo, we need an additional term to the loss. If this term is from Apollo, we need to find a way to propagate its gradients.

**Comment by evanatyourservice** [comment]
Okay yeah I was just curious, I bet it would have to be part of the loss but then this would defeat the purpose of apollo's speed, having to do a second order type thing. Thank you for answering! Interestingly apollo doesn't work with sharpness aware minimization, something with the noised model prevents apollo from getting an accurate hessian estimate. Edit: At least with my transformer experiments, not sure with cnns or other networks.
